version: '3.3'

services:
  gRPC-server:
    image: indiependente/gw-example-server
    ports:
     - 8080:8080
     - 9090:9090
  gRPC-client:
    image: indiependente/gw-example-client
    environment:
      SERVER_ADDR: gRPC-server
      PORT: 9090
    links:
      - gRPC-server
