version: '3.3'

services:
  gRPC-server:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
     - 8080:8080
     - 9090:9090
  gRPC-client:
    build: 
      context: .
      dockerfile: ./client/Dockerfile
    environment:
      SERVER_ADDR: gRPC-server
      PORT: 9090
    links:
      - gRPC-server
